import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'fr' | 'en';

const fr = {
  // ---------- Navbar / common ----------
  home: "Accueil", services: "Services", howItWorks: "Comment ça marche",
  login: "Connexion", logout: "Déconnexion", register: "S'inscrire",
  myOrders: "Mes commandes", myMissions: "Mes missions", myGigs: "Mes gigs",
  myProfile: "Mon profil", myRequests: "Mes demandes", myProposals: "Mes propositions",
  adminDashboard: "Dashboard Admin", modDashboard: "Dashboard Modérateur",
  student: "Étudiant", moderator: "Modérateur", client: "Client", admin: "Admin",
  requests: "Demandes",
  // ---------- Admin (existant) ----------
  administration: "Administration", dashboard: "Tableau de bord",
  users: "Utilisateurs", verifications: "Vérifications", orders: "Commandes",
  moderation: "Modération", categories: "Catégories", reports: "Rapports",
  search: "Rechercher...", activeUsers: "Utilisateurs", revenue: "Revenus (FCFA)",
  disputes: "Litiges", identityVerification: "Vérifications d'identité",
  allProcessed: "Tout est traité !", userManagement: "Gestion des utilisateurs",
  reportedContent: "Contenus signalés", approve: "Approuver et attribuer le badge",
  reject: "Rejeter", verified: "Identité vérifiée ✓", rejected: "Identité rejetée",
  badgeAssigned: "Le badge 'Étudiant Vérifié' a été attribué.",
  willBeNotified: "L'étudiant sera notifié.", suspended: "Compte suspendu",
  banned: "Compte banni", reactivated: "Compte réactivé", contentRemoved: "Contenu supprimé",
  reportDismissed: "Signalement rejeté", refundDone: "Remboursement effectué",
  exportLaunched: "Export lancé", downloadSoon: "Le fichier sera téléchargé sous peu.",
  categoryAdded: "Catégorie ajoutée", cityAdded: "Ville ajoutée",
  newCategory: "Nouvelle catégorie", newCity: "Nouvelle ville", cities: "Villes",
  active: "Actif", inactive: "Inactif", config: "Configuration",
  email: "Email", university: "Université", documentType: "Type de pièce",
  submitted: "Soumis", idDocument: "Pièce d'identité", studentCard: "Carte étudiante",
  verificationSelfie: "Selfie de vérification", role: "Rôle", city: "Ville",
  status: "Statut", joined: "Inscrit", actions: "Actions", type: "Type",
  description: "Description", reportedBy: "Signalé par", reason: "Raison",
  amount: "Montant", service: "Service", refund: "Rembourser",
  completed: "Terminé", inProgress: "En cours", disputed: "Litige", pending: "En attente",
  lightMode: "Mode clair", darkMode: "Mode sombre",
  // ---------- Common ----------
  c_back: "Retour", c_save: "Enregistrer", c_cancel: "Annuler", c_confirm: "Confirmer",
  c_send: "Envoyer", c_loading: "Chargement...", c_submit: "Soumettre",
  c_publish: "Publier", c_create: "Créer", c_delete: "Supprimer", c_edit: "Modifier",
  c_close: "Fermer", c_yes: "Oui", c_no: "Non", c_error: "Erreur",
  c_required: "Requis", c_optional: "optionnel", c_none: "Aucun",
  c_all: "Toutes", c_search: "Rechercher", c_view: "Voir",
  c_next: "Suivant", c_previous: "Précédent",
  c_history: "Historique", c_stats: "Statistiques", c_metric: "Métrique", c_value: "Valeur",
  c_err_invalid_price: "Le prix ou budget doit être supérieur à 0.",
  c_err_required_fields: "Veuillez remplir tous les champs obligatoires.",
  lvl_beginner: "Débutant", lvl_intermediate: "Intermédiaire",
  lvl_advanced: "Avancé", lvl_expert: "Expert",
  // ---------- Hero ----------
  hero_badge: "Étudiants vérifiés · Paiement sécurisé",
  hero_title1: "Le talent étudiant,", hero_title2: "à votre service",
  hero_subtitle: "Kam'Etud connecte les étudiants camerounais talentueux avec les familles et PME qui ont besoin de leurs compétences. Cours, développement web, aide à domicile et plus encore.",
  hero_cta1: "Trouver un service", hero_cta2: "Devenir prestataire",
  hero_stat1: "étudiants inscrits", hero_stat2: "& bientôt tout le Cameroun",
  hero_stat3a: "Paiement", hero_stat3b: "Mobile Money",
  // ---------- Categories section ----------
  cats_title1: "Des services pour", cats_title2: "chaque besoin",
  cats_subtitle: "7 catégories de services proposés par des étudiants vérifiés de l'Université de Dschang.",
  cats_providers: "prestataires",
  cat_acad: "Académique", cat_acad_d: "Cours, répétition, rédaction de mémoire, traduction",
  cat_num: "Numérique", cat_num_d: "Dev web, design graphique, montage vidéo, réseaux sociaux",
  cat_home: "Aide à domicile", cat_home_d: "Ménage, cuisine, garde d'enfants, assistance",
  cat_deliv: "Livraison & Courses", cat_deliv_d: "Livraison de colis, courses supermarché, commissions",
  cat_bric: "Bricolage", cat_bric_d: "Montage meuble, peinture, petite plomberie, électricité",
  cat_event: "Événementiel", cat_event_d: "Accueil, animation, décoration, service traiteur",
  cat_beauty: "Beauté & Bien-être", cat_beauty_d: "Coiffure à domicile, maquillage, soins ongles",
  // ---------- How it works section ----------
  how_title1: "Comment ça", how_title2: "marche",
  how_subtitle: "Simple, rapide et sécurisé. Quatre étapes pour accéder au talent étudiant.",
  how_s1_t: "Recherchez", how_s1_d: "Parcourez les services par catégorie ou utilisez la carte interactive pour trouver un étudiant près de chez vous.",
  how_s2_t: "Contactez", how_s2_d: "Décrivez votre besoin et échangez avec l'étudiant pour définir les détails de la mission.",
  how_s3_t: "Payez en sécurité", how_s3_d: "Payez via Mobile Money (MTN MoMo ou Orange Money). Les fonds sont sécurisés jusqu'à la livraison.",
  how_s4_t: "Validez & notez", how_s4_d: "Recevez le travail, validez la livraison et notez l'étudiant pour aider la communauté.",
  // ---------- Trust section ----------
  trust_title1: "Pourquoi choisir", trust_title2: "Kam'Etud",
  trust_f1_t: "Identité vérifiée", trust_f1_d: "Chaque étudiant est vérifié avec sa carte d'étudiant et sa CNI. Badge de confiance garanti.",
  trust_f2_t: "Paiement Mobile Money", trust_f2_d: "Payez via MTN MoMo ou Orange Money. Fonds sécurisés par séquestre jusqu'à validation.",
  trust_f3_t: "CV numérique", trust_f3_d: "Chaque mission réalisée enrichit le profil de l'étudiant. Générez un CV PDF professionnel.",
  trust_f4_t: "Matching intelligent", trust_f4_d: "Notre algorithme trouve le prestataire idéal selon vos besoins, la proximité et les notes.",
  // ---------- CTA ----------
  cta_title1: "Tu es étudiant ?", cta_title2: "Monétise tes compétences.",
  cta_subtitle: "Inscris-toi, vérifie ton identité et commence à proposer tes services. Construis ton CV numérique mission après mission.",
  cta_btn1: "Créer mon profil", cta_btn2: "En savoir plus",
  // ---------- Footer ----------
  ft_tagline: "Transformer le talent étudiant en levier d'autonomie financière et d'expérience professionnelle.",
  ft_platform: "Plateforme", ft_support: "Support", ft_cities: "Villes",
  ft_help: "Centre d'aide", ft_contact: "Contact",
  ft_terms: "Conditions d'utilisation", ft_privacy: "Confidentialité",
  ft_cgu: "CGU",
  ft_copy: "© 2026 Kam'Etud — Université de Dschang. Tous droits réservés.",
  // ---------- Services page ----------
  sv_title1: "Explorer les", sv_title2: "services",
  sv_subtitle: "Trouvez l'étudiant idéal parmi nos prestataires vérifiés.",
  sv_search: "Rechercher un service ou un prestataire...",
  sv_city: "Ville", sv_rating: "Note min.", sv_distance: "Distance",
  sv_geo_loc: "Localisé", sv_geo_btn: "Près de moi",
  sv_geo_unavail: "Géolocalisation non disponible", sv_geo_ok: "Position trouvée !",
  sv_geo_err: "Impossible d'obtenir votre position",
  sv_reset: "Réinitialiser", sv_all: "Tous",
  sv_results: "résultat", sv_results_plural: "résultats",
  sv_reviews: "avis", sv_from: "À partir de", sv_none: "Aucun service trouvé.",
  sv_map_pos: "Votre position",
  // ---------- HowItWorks page ----------
  hw_title1: "Comment fonctionne", hw_title2: "Kam'Etud",
  hw_subtitle: "Une plateforme pensée pour les étudiants camerounais et adaptée aux réalités locales.",
  hw_escrow_t1: "Paiement", hw_escrow_t2: "sécurisé par séquestre",
  hw_e1_t: "Le client paie à la commande", hw_e1_d: "Les fonds sont envoyés via MTN MoMo ou Orange Money et bloqués par Kam'Etud.",
  hw_e2_t: "L'étudiant réalise la mission", hw_e2_d: "Pour les grandes missions (>10 000 FCFA), le paiement se fait en 3 tranches : 30% / 30% / 40%.",
  hw_e3_t: "Validation et déblocage", hw_e3_d: "Le client valide le livrable, les fonds sont libérés vers le compte Mobile Money de l'étudiant sous 24h.",
  // ---------- Privacy / Terms ----------
  pr_title: "Politique de confidentialité", pr_updated: "Dernière mise à jour",
  pr_h1: "1. Données collectées",
  pr_p1: "Kam'Etud collecte uniquement les données nécessaires au bon fonctionnement de la plateforme : nom, prénom, email, téléphone, ville, université, photo de profil, documents d'identité (CNI, carte étudiant, selfie) pour la vérification KYC, ainsi que l'historique de vos commandes et messages.",
  pr_h2: "2. Utilisation des données",
  pr_p2: "Vos données servent à : créer et sécuriser votre compte, mettre en relation clients et étudiants freelances, traiter les paiements en mode escrow, modérer la plateforme et améliorer nos services.",
  pr_h3: "3. Partage des données",
  pr_p3: "Aucune donnée n'est revendue à des tiers. Les documents KYC sont consultables uniquement par notre équipe d'administration et de modération.",
  pr_h4: "4. Stockage et sécurité",
  pr_p4: "Les données sont stockées sur des serveurs sécurisés (chiffrement en transit et au repos). Les documents d'identité sont conservés dans un espace privé accessible via URL signée temporaire.",
  pr_h5: "5. Vos droits",
  pr_p5a: "Conformément à la loi camerounaise n°2010/012 sur la cybersécurité et la cybercriminalité, vous disposez d'un droit d'accès, de rectification et de suppression de vos données. Contactez-nous à",
  pr_h6: "6. Cookies",
  pr_p6: "Nous utilisons uniquement les cookies strictement nécessaires (session d'authentification, préférences thème et langue).",
  tm_title: "Conditions Générales d'Utilisation",
  tm_h1: "1. Objet", tm_p1: "Kam'Etud est une plateforme camerounaise mettant en relation des étudiants freelances vérifiés et des clients à la recherche de services (cours, design, rédaction, programmation, etc.).",
  tm_h2: "2. Inscription", tm_p2: "L'inscription est gratuite. Les étudiants doivent fournir une CNI, une carte étudiant et un selfie pour obtenir le badge « Vérifié » avant de publier des services ou répondre à des demandes.",
  tm_h3: "3. Paiement & Escrow", tm_p3: "Les paiements se font exclusivement en FCFA via Mobile Money. Les fonds sont sécurisés en escrow et libérés à l'étudiant 24h après la livraison validée par le client, sauf litige.",
  tm_h4: "4. Révisions & Litiges", tm_p4: "Chaque commande inclut 2 révisions maximum. En cas de désaccord, un modérateur Kam'Etud tranche le litige (libération des fonds à l'étudiant ou remboursement au client).",
  tm_h5: "5. Comportement", tm_p5: "Toute fraude, harcèlement, contenu illégal ou tentative de paiement hors plateforme entraîne la suspension immédiate du compte et la perte des fonds en escrow.",
  tm_h6: "6. Commission", tm_p6: "Kam'Etud prélève une commission de service sur chaque transaction réussie pour couvrir le fonctionnement de la plateforme.",
  tm_h7: "7. Responsabilité", tm_p7: "Kam'Etud joue un rôle d'intermédiaire. La qualité du travail livré relève de la responsabilité de l'étudiant ; le respect du cahier des charges et du paiement relève du client.",
  tm_h8: "8. Loi applicable", tm_p8: "Les présentes CGU sont régies par le droit camerounais. Tout litige sera soumis aux tribunaux de Dschang.",
  nf_title: "Oups ! Page introuvable", nf_home: "Retour à l'accueil",
  // ---------- Auth ----------
  au_welcome_subtitle: "Accédez à votre compte",
  au_google_signin: "Se connecter avec Google", au_google_signup: "S'inscrire avec Google",
  au_or: "ou", au_or_email: "ou avec un email",
  au_email: "Email", au_password: "Mot de passe",
  au_phone: "Téléphone", au_phone_number: "Numéro de téléphone",
  au_forgot: "Oublié ?", au_login: "Se connecter", au_logging: "Connexion...",
  au_send_otp: "Envoyer le code OTP", au_sending: "Envoi...",
  au_verify: "Vérifier et se connecter", au_verifying: "Vérification...",
  au_resend: "Renvoyer le code", au_otp_label: "Code OTP (6 chiffres)",
  au_login_ok: "Connexion réussie", au_login_welcome: "Bienvenue sur Kam'Etud !",
  au_err_creds: "Email ou mot de passe incorrect.", au_err_otp: "Code OTP invalide.",
  au_otp_sent: "Code envoyé !", au_otp_sent_desc: "Un code OTP a été envoyé au",
  au_otp_err: "Impossible d'envoyer le code.",
  au_no_account: "Pas encore de compte ?", au_have_account: "Déjà un compte ?",
  au_signup: "S'inscrire", au_signin: "Se connecter",
  au_create_account: "Créer un compte", au_choose_profile: "Choisissez votre profil pour commencer",
  au_complete_later: "Vous pourrez compléter votre profil ensuite",
  au_student_t: "Étudiant", au_student_d: "Proposez vos compétences et gagnez de l'argent en aidant les autres",
  au_client_t: "Client", au_client_d: "Trouvez des étudiants talentueux pour vos projets et missions",
  au_signup_student: "Inscription Étudiant", au_signup_student_sub: "Rejoignez la communauté et proposez vos services",
  au_signup_client: "Inscription Client", au_signup_client_sub: "Trouvez des étudiants talentueux pour vos projets",
  au_first_name: "Prénom", au_last_name: "Nom", au_confirm: "Confirmer",
  au_confirm_pw: "Confirmer le mot de passe", au_pw_mismatch: "Les mots de passe ne correspondent pas",
  au_pw_hint: "Min. 8 caractères", au_city: "Ville", au_city_yours: "Votre ville",
  au_creating: "Création...", au_create_btn: "Créer mon compte",
  au_step1: "Informations personnelles", au_step2: "Profil académique", au_step3: "Vérification d'identité",
  au_faculty: "Faculté / Filière", au_faculty_eg: "Ex: Informatique",
  au_level: "Niveau", au_level_select: "Sélectionnez",
  au_uni: "Université", au_bio: "Bio", au_bio_hint: "Présentez-vous...",
  au_skills: "Compétences (min. 1)", au_doc_type: "Type de pièce d'identité",
  au_doc_select: "Choisir", au_doc_warn: "Vos documents seront vérifiés par un administrateur avant d'activer votre compte.",
  au_id_photo: "Photo de la pièce d'identité", au_id_drop: "Glissez ou cliquez",
  au_selfie: "Selfie avec pièce d'identité", au_selfie_hint: "Prenez un selfie",
  au_student_card: "Carte étudiante (optionnel)", au_student_card_hint: "Carte étudiante",
  au_accept: "J'accepte les", au_terms: "conditions", au_and: "et la", au_privacy: "politique de confidentialité",
  au_sent: "Inscription envoyée !", au_sent_d: "Vérifiez votre email puis connectez-vous pour compléter la vérification.",
  au_err_register: "Erreur lors de l'inscription. Vérifiez vos informations.",
  au_signup_ok: "Inscription réussie !", au_signup_ok_d: "Vérifiez votre email pour activer votre compte.",
  au_or_student: "Inscription étudiant", au_or_client: "Inscription client",
  au_google_redir: "Redirection...", au_google_err: "Erreur Google",
  au_continue_google: "Continuer avec Google",
  // ---------- Profile ----------
  pf_verified: "Vérifié", pf_member_since: "Membre depuis",
  pf_not_set: "Non renseigné", pf_contact: "Contacter",
  pf_cv: "CV", pf_photo: "Photo",
  pf_change_photo: "Changer la photo de profil",
  pf_about: "À propos",
  pf_format_invalid: "Format invalide", pf_format_d: "JPG ou PNG uniquement.",
  pf_too_big: "Fichier trop lourd", pf_too_big_d: "Maximum 5 Mo.",
  pf_photo_ok: "Photo mise à jour", pf_photo_del: "Photo supprimée",
  pf_del_confirm: "Supprimer votre photo de profil ?",
  pf_up_err: "Erreur upload", pf_del_err: "Erreur suppression",
  pf_stat_rating: "Note", pf_stat_missions: "Missions",
  pf_stat_reviews: "Avis", pf_stat_response: "Réponse",
  pf_progress: "Progression",
  pf_tab_services: "Services", pf_tab_reviews: "Avis", pf_tab_skills: "Compétences",
  pf_order: "Commander", pf_orders_count: "commandes", pf_included: "inclus",
  pf_days_short: "j",
  pf_cv_gen: "Généré le", pf_cv_city: "Ville :", pf_cv_intro: "Présentation",
  pf_cv_skills: "Compétences", pf_cv_jobs: "Missions réalisées",
  pf_cv_rating: "Note moyenne", pf_cv_level: "Niveau", pf_cv_response: "Temps de réponse",
  pf_cv_offered: "Service proposé", pf_cv_from: "À partir de",
  pf_cv_footer: "Généré sur Kam'Etud — la plateforme camerounaise des étudiants freelances",
  pf_cv_title: "Kam'Etud — CV",
  // ---------- OrderPage ----------
  op_gig_404: "Gig introuvable",
  op_h: "Passer commande", op_by: "par",
  op_choose_tier: "Choisir une formule",
  op_describe: "Décrivez votre mission",
  op_describe_ph: "Décrivez précisément ce que vous attendez...",
  op_secure_pay: "Paiement sécurisé",
  op_escrow_t: "Paiement par escrow :",
  op_escrow_d: "Argent bloqué jusqu'à validation.",
  op_phone: "Numéro de téléphone",
  op_summary: "Résumé", op_tier: "Formule", op_provider: "Prestataire",
  op_delay: "Délai", op_total: "Total",
  op_pay_btn: "Payer", op_processing: "Traitement...",
  op_escrow_caption: "Paiement sécurisé par escrow",
  op_login_required: "Connectez-vous", op_login_required_d: "Vous devez être connecté pour commander.",
  op_demo: "Démo", op_demo_d: "Ceci est un service de démonstration. Créez de vrais gigs pour passer commande.",
  op_mm_pending: "Paiement Mobile Money en attente",
  op_mm_pending_d: "Commande créée. Le prélèvement a échoué — réessayez depuis Mes commandes.",
  op_validate_phone: "Validez sur votre téléphone",
  op_ussd: "Composez", op_to_confirm: "pour confirmer",
  op_request_sent_to: "Une demande de",
  op_has_been_sent_to: "a été envoyée au",
  // ---------- Order status ----------
  st_pending: "En attente", st_accepted: "Accepté", st_in_progress: "En cours",
  st_delivered: "Livré", st_revision: "Révision demandée", st_revision_short: "Révision",
  st_completed: "Terminé", st_disputed: "Litige",
  st_cancelled: "Annulé", st_refunded: "Remboursé",
  // ---------- MyOrders / MyMissions ----------
  mo_title: "Mes commandes", mo_active: "En cours", mo_past: "Terminées",
  mo_none_active: "Aucune commande en cours", mo_none_past: "Aucune commande passée",
  mo_explore: "Explorer", mo_by: "Par", mo_tier: "Formule",
  mo_deliverable: "Livrable soumis", mo_deliverable_default: "L'étudiant a soumis le livrable.",
  mo_validate: "Valider", mo_revision: "Révision", mo_dispute: "Contester",
  mo_review: "Noter", mo_publish: "Publier",
  mo_review_for: "Noter", mo_review_ph: "Votre avis...",
  mo_chat: "Chat", mo_send: "Envoyer", mo_msg_ph: "Votre message...",
  mo_revision_asked: "Révision demandée", mo_dispute_open: "Litige ouvert",
  mo_thanks: "Merci !",
  mo_valid_ok: "Livrable accepté !", mo_valid_ok_d: "Paiement libéré vers l'étudiant via Mobile Money.",
  mo_valid_pending: "Livrable validé", mo_valid_pending_d: "Paiement vers l'étudiant en cours — il sera libéré sous peu.",
  mm_title: "Mes missions", mm_demands: "Demandes",
  mm_active: "En cours", mm_done: "Terminées",
  mm_none_pending: "Aucune demande", mm_none_active: "Aucune mission active",
  mm_none_done: "Aucune mission terminée",
  mm_client: "Client", mm_delivery: "Livraison", mm_revisions: "Révisions",
  mm_accept: "Accepter", mm_decline: "Refuser",
  mm_accepted: "Mission acceptée !", mm_declined: "Mission refusée",
  mm_submit: "Soumettre le livrable", mm_dragdrop: "Glissez vos fichiers ici",
  mm_note_client: "Note pour le client...", mm_default_note: "Livrable soumis",
  mm_submitted: "Livrable soumis !", mm_chat_client: "Chat client",
  mm_no_msg: "Aucun message pour l'instant.",
  // ---------- MyGigs / CreateGig ----------
  mg_title: "Mes Gigs", mg_create: "Créer un gig",
  mg_none: "Vous n'avez aucun gig. Créez votre premier service !",
  mg_status_ok: "Statut mis à jour", mg_deleted: "Gig supprimé",
  mg_published: "Publié", mg_unpublished: "Dépublié",
  mg_draft: "Brouillon", mg_orders_count: "commandes",
  mg_kyc_req: "Vérification requise", mg_kyc_req_d: "Vous devez être vérifié (KYC) pour publier un gig.",
  mg_unpublish: "Dépublier", mg_publish: "Publier",
  cg_title: "Publier un nouveau gig", cg_general: "Informations générales",
  cg_gig_title: "Titre", cg_gig_title_ph: "Ex: Création de site web",
  cg_gig_desc: "Description", cg_gig_desc_ph: "Décrivez votre service...",
  cg_category: "Catégorie", cg_choose: "Choisir",
  cg_pricing: "Tarification (3 paliers)",
  cg_price: "Prix (FCFA)", cg_delay: "Délai (jours)",
  cg_tier_desc: "Description", cg_tier_desc_ph: "Ex: Landing page",
  cg_included: "Inclus", cg_feature_ph: "Ex: Design responsive",
  cg_add: "Ajouter",
  cg_publish_now: "Publier maintenant",
  cg_pn_yes: "Votre service sera visible par les clients.",
  cg_pn_no: "Indisponible : votre identité doit être vérifiée par un admin.",
  cg_warn: "Vous pouvez créer des gigs en", cg_warn_b: "brouillon",
  cg_warn_2: ". Ils ne seront publiés qu'après validation KYC par un administrateur.",
  cg_saving: "Enregistrement...", cg_publish_btn: "Publier le gig",
  cg_save_draft: "Enregistrer en brouillon",
  cg_gig_published: "Gig publié !", cg_gig_published_d: "Votre service est maintenant visible.",
  cg_draft_saved: "Brouillon enregistré", cg_draft_saved_d: "Vous pourrez le publier après validation de votre identité.",
  // ---------- Requests ----------
  rq_title: "Demandes ouvertes",
  rq_subtitle: "Les clients publient leur besoin et leur prix, les étudiants proposent",
  rq_new: "Publier une demande", rq_new_modal: "Nouvelle demande",
  rq_title_f: "Titre", rq_title_ph: "Ex: Création d'un logo",
  rq_desc: "Description", rq_desc_ph: "Décrivez votre besoin...",
  rq_budget: "Budget (FCFA)", rq_deadline: "Échéance",
  rq_publishing: "Publication...", rq_publish: "Publier",
  rq_posted: "Demande publiée", rq_posted_d: "Les étudiants peuvent maintenant proposer un prix.",
  rq_none: "Aucune demande ouverte pour le moment.",
  rq_by: "par", rq_budget_caption: "Budget proposé",
  // ---------- RequestDetail ----------
  rd_404: "Demande introuvable", rd_cancel: "Annuler la demande",
  rd_cancelled: "Demande annulée",
  rd_propose: "Faire une proposition (renégocier le prix)",
  rd_your_price: "Votre prix (FCFA)", rd_delay: "Délai (jours)",
  rd_message: "Message", rd_message_ph: "Expliquez votre approche...",
  rd_sending: "Envoi...", rd_send: "Envoyer la proposition",
  rd_sent: "Proposition envoyée",
  rd_must_verify: "Vous devez être vérifié pour proposer un prix.",
  rd_proposals: "Propositions reçues",
  rd_no_proposals: "Aucune proposition pour l'instant.",
  rd_delay_days: "jour(s)",
  rd_accept: "Accepter", rd_accepted: "Proposition acceptée",
  rd_accepted_d: "L'étudiant sera notifié.",
  // ---------- MyRequests ----------
  mr_title: "Mes demandes", mr_new: "Nouvelle demande",
  mr_none: "Vous n'avez pas encore publié de demande.",
  mr_publish: "Publier une demande",
  mr_st_open: "Ouverte", mr_st_assigned: "Assignée",
  mr_st_cancelled: "Annulée", mr_st_closed: "Clôturée",
  // ---------- Proposals ----------
  prp_title: "Mes propositions", prp_none: "Vous n'avez pas encore fait de proposition.",
  prp_status_pending: "En attente", prp_status_accepted: "Acceptée", prp_status_rejected: "Refusée",
  prp_view_mission: "Voir la mission",
  // ---------- Income / Wallet ----------
  inc_title: "💰 Mon Revenu", inc_available: "Solde disponible",
  inc_pending: "En attente (Escrow)", inc_paid_missions: "Missions payées",
  inc_payout_settings: "Paramètres de retrait", inc_payout_phone: "Numéro Mobile Money (pour vos paiements)",
  inc_payout_help: "Ce numéro sera utilisé pour vous envoyer vos gains après chaque mission validée.",
  inc_payout_ok: "Numéro de retrait mis à jour",
  // ---------- Moderator ----------
  md_disputes: "Litiges", md_reports: "Signalements",
  md_title: "Gestion des litiges", md_navigation: "Navigation",
  md_open: "Litiges ouverts", md_resolved: "Résolus",
  md_avg_time: "Temps moyen", md_open_status: "Ouvert",
  md_tab_open: "Ouverts", md_tab_resolved: "Résolus",
  md_none_open: "Aucun litige", md_none_resolved: "Aucun litige résolu",
  md_arbitrate: "Arbitrer", md_arbitration: "Arbitrage",
  md_note_ph: "Note du modérateur...",
  md_refund: "Rembourser", md_validate: "Valider livrable",
  md_report_abuse: "Signaler abus",
  md_resolved_ok: "Litige résolu",
  md_refund_ordered: "Remboursement ordonné", md_deliverable_validated: "Livrable validé",
  md_escalated: "Signalé à l'administrateur",
  md_refunded: "Remboursé", md_validated: "Validé",
  // ---------- Notifications (realtime) ----------
  nt_new_msg: "Nouveau message",
  nt_status: "Statut",
  nt_new_mission: "Nouvelle mission",
  nt_title: "Notifications", nt_mark_read: "Lu", nt_none: "Aucune notification",
  ad_loading_img: "Chargement…", ad_no_docs: "Aucun document uploadé",
  ad_no_users: "Aucun utilisateur trouvé", ad_no_reports: "Aucun contenu signalé",
  ad_no_text: "Sans texte", ad_no_orders: "Aucune commande",
  ad_no_cats: "Aucune catégorie", ad_no_cities: "Aucune ville",
  ad_preview_img: "Aperçu image", ad_zoom_in: "Zoomer", ad_zoom_out: "Dézoomer",
  ad_reset_zoom: "Réinitialiser", ad_download: "Télécharger",
  ad_preview: "Aperçu", ad_download_err: "Téléchargement impossible",
  ad_report_title: "Kam'Etud — Rapport Admin",
  md_validate_deliv: "Valider livrable",
};

const en: typeof fr = {
  home: "Home", services: "Services", howItWorks: "How it works",
  login: "Login", logout: "Logout", register: "Sign up",
  myOrders: "My orders", myMissions: "My missions", myGigs: "My gigs",
  myProfile: "My profile", myRequests: "My requests", myProposals: "My proposals",
  adminDashboard: "Admin Dashboard", modDashboard: "Moderator Dashboard",
  student: "Student", moderator: "Moderator", client: "Client", admin: "Admin",
  requests: "Requests",
  administration: "Administration", dashboard: "Dashboard",
  users: "Users", verifications: "Verifications", orders: "Orders",
  moderation: "Moderation", categories: "Categories", reports: "Reports",
  search: "Search...", activeUsers: "Users", revenue: "Revenue (FCFA)",
  disputes: "Disputes", identityVerification: "Identity Verifications",
  allProcessed: "All processed!", userManagement: "User Management",
  reportedContent: "Reported Content", approve: "Approve and assign badge",
  reject: "Reject", verified: "Identity verified ✓", rejected: "Identity rejected",
  badgeAssigned: "The 'Verified Student' badge has been assigned.",
  willBeNotified: "The student will be notified.", suspended: "Account suspended",
  banned: "Account banned", reactivated: "Account reactivated", contentRemoved: "Content removed",
  reportDismissed: "Report dismissed", refundDone: "Refund completed",
  exportLaunched: "Export launched", downloadSoon: "File will be downloaded shortly.",
  categoryAdded: "Category added", cityAdded: "City added",
  newCategory: "New category", newCity: "New city", cities: "Cities",
  active: "Active", inactive: "Inactive", config: "Configuration",
  email: "Email", university: "University", documentType: "Document type",
  submitted: "Submitted", idDocument: "ID Document", studentCard: "Student Card",
  verificationSelfie: "Verification Selfie", role: "Role", city: "City",
  status: "Status", joined: "Joined", actions: "Actions", type: "Type",
  description: "Description", reportedBy: "Reported by", reason: "Reason",
  amount: "Amount", service: "Service", refund: "Refund",
  completed: "Completed", inProgress: "In progress", disputed: "Disputed", pending: "Pending",
  lightMode: "Light mode", darkMode: "Dark mode",
  c_back: "Back", c_save: "Save", c_cancel: "Cancel", c_confirm: "Confirm",
  c_send: "Send", c_loading: "Loading...", c_submit: "Submit",
  c_publish: "Publish", c_create: "Create", c_delete: "Delete", c_edit: "Edit",
  c_close: "Close", c_yes: "Yes", c_no: "No", c_error: "Error",
  c_required: "Required", c_optional: "optional", c_none: "None",
  c_all: "All", c_search: "Search", c_view: "View",
  c_next: "Next", c_previous: "Previous",
  c_history: "History", c_stats: "Statistics", c_metric: "Metric", c_value: "Value",
  c_err_invalid_price: "Price or budget must be greater than 0.",
  c_err_required_fields: "Please fill in all required fields.",
  lvl_beginner: "Beginner", lvl_intermediate: "Intermediate",
  lvl_advanced: "Advanced", lvl_expert: "Expert",
  // ---------- Hero ----------
  hero_badge: "Verified students · Secure payments",
  hero_title1: "Student talent,", hero_title2: "at your service",
  hero_subtitle: "Kam'Etud connects talented Cameroonian students with families and SMBs who need their skills. Tutoring, web development, home help and more.",
  hero_cta1: "Find a service", hero_cta2: "Become a provider",
  hero_stat1: "registered students", hero_stat2: "& soon all of Cameroon",
  hero_stat3a: "Pay with", hero_stat3b: "Mobile Money",
  cats_title1: "Services for", cats_title2: "every need",
  cats_subtitle: "7 service categories offered by verified students from the University of Dschang.",
  cats_providers: "providers",
  cat_acad: "Academic", cat_acad_d: "Tutoring, repetition, thesis writing, translation",
  cat_num: "Digital", cat_num_d: "Web dev, graphic design, video editing, social media",
  cat_home: "Home help", cat_home_d: "Cleaning, cooking, childcare, assistance",
  cat_deliv: "Delivery & Errands", cat_deliv_d: "Parcel delivery, grocery shopping, errands",
  cat_bric: "Handywork", cat_bric_d: "Furniture assembly, painting, light plumbing, electrical",
  cat_event: "Events", cat_event_d: "Reception, animation, decoration, catering",
  cat_beauty: "Beauty & Wellness", cat_beauty_d: "Home hairstyling, makeup, nail care",
  how_title1: "How it", how_title2: "works",
  how_subtitle: "Simple, fast and secure. Four steps to access student talent.",
  how_s1_t: "Search", how_s1_d: "Browse services by category or use the interactive map to find a student near you.",
  how_s2_t: "Contact", how_s2_d: "Describe your need and chat with the student to define the mission details.",
  how_s3_t: "Pay securely", how_s3_d: "Pay via Mobile Money (MTN MoMo or Orange Money). Funds are held safely until delivery.",
  how_s4_t: "Validate & rate", how_s4_d: "Receive the work, validate delivery and rate the student to help the community.",
  trust_title1: "Why choose", trust_title2: "Kam'Etud",
  trust_f1_t: "Verified identity", trust_f1_d: "Every student is verified with their student card and ID. Trust badge guaranteed.",
  trust_f2_t: "Mobile Money payment", trust_f2_d: "Pay via MTN MoMo or Orange Money. Funds secured in escrow until validation.",
  trust_f3_t: "Digital CV", trust_f3_d: "Every completed mission enriches the student's profile. Generate a professional PDF CV.",
  trust_f4_t: "Smart matching", trust_f4_d: "Our algorithm finds the ideal provider based on your needs, proximity and ratings.",
  cta_title1: "Are you a student?", cta_title2: "Monetize your skills.",
  cta_subtitle: "Sign up, verify your identity and start offering your services. Build your digital CV mission after mission.",
  cta_btn1: "Create my profile", cta_btn2: "Learn more",
  ft_tagline: "Turning student talent into a lever for financial independence and professional experience.",
  ft_platform: "Platform", ft_support: "Support", ft_cities: "Cities",
  ft_help: "Help center", ft_contact: "Contact",
  ft_terms: "Terms of use", ft_privacy: "Privacy",
  ft_cgu: "Terms",
  ft_copy: "© 2026 Kam'Etud — University of Dschang. All rights reserved.",
  sv_title1: "Explore", sv_title2: "services",
  sv_subtitle: "Find the right student among our verified providers.",
  sv_search: "Search a service or a provider...",
  sv_city: "City", sv_rating: "Min rating", sv_distance: "Distance",
  sv_geo_loc: "Located", sv_geo_btn: "Near me",
  sv_geo_unavail: "Geolocation unavailable", sv_geo_ok: "Position found!",
  sv_geo_err: "Could not get your position",
  sv_reset: "Reset", sv_all: "All",
  sv_results: "result", sv_results_plural: "results",
  sv_reviews: "reviews", sv_from: "From", sv_none: "No service found.",
  sv_map_pos: "Your location",
  hw_title1: "How", hw_title2: "Kam'Etud works",
  hw_subtitle: "A platform designed for Cameroonian students and adapted to local realities.",
  hw_escrow_t1: "Payment", hw_escrow_t2: "secured by escrow",
  hw_e1_t: "Client pays at checkout", hw_e1_d: "Funds are sent via MTN MoMo or Orange Money and held by Kam'Etud.",
  hw_e2_t: "Student completes the mission", hw_e2_d: "For large missions (>10,000 FCFA), payment is split in 3: 30% / 30% / 40%.",
  hw_e3_t: "Validation and release", hw_e3_d: "The client validates the delivery, funds are released to the student's Mobile Money account within 24h.",
  pr_title: "Privacy Policy", pr_updated: "Last updated",
  pr_h1: "1. Data collected",
  pr_p1: "Kam'Etud only collects the data needed to operate the platform: first/last name, email, phone, city, university, profile photo, identity documents (ID, student card, selfie) for KYC verification, plus your order and message history.",
  pr_h2: "2. Use of data",
  pr_p2: "Your data is used to: create and secure your account, match clients with student freelancers, process escrow payments, moderate the platform and improve our services.",
  pr_h3: "3. Data sharing",
  pr_p3: "No data is sold to third parties. KYC documents are only accessible to our admin and moderation team.",
  pr_h4: "4. Storage & security",
  pr_p4: "Data is stored on secure servers (encryption in transit and at rest). ID documents are kept in a private space accessible via temporary signed URLs.",
  pr_h5: "5. Your rights",
  pr_p5a: "In accordance with Cameroonian law 2010/012 on cybersecurity and cybercrime, you have a right of access, correction and deletion of your data. Contact us at",
  pr_h6: "6. Cookies",
  pr_p6: "We only use strictly necessary cookies (auth session, theme and language preferences).",
  tm_title: "Terms and Conditions",
  tm_h1: "1. Purpose", tm_p1: "Kam'Etud is a Cameroonian platform connecting verified student freelancers with clients looking for services (tutoring, design, writing, programming, etc.).",
  tm_h2: "2. Registration", tm_p2: "Registration is free. Students must provide an ID, student card and selfie to earn the “Verified” badge before publishing services or replying to requests.",
  tm_h3: "3. Payment & Escrow", tm_p3: "Payments are made exclusively in FCFA via Mobile Money. Funds are secured in escrow and released to the student 24h after the client validates the delivery, except in case of dispute.",
  tm_h4: "4. Revisions & Disputes", tm_p4: "Each order includes up to 2 revisions. In case of disagreement, a Kam'Etud moderator settles the dispute (release of funds to the student or refund to the client).",
  tm_h5: "5. Behavior", tm_p5: "Any fraud, harassment, illegal content or attempt to pay outside the platform leads to immediate account suspension and loss of escrow funds.",
  tm_h6: "6. Commission", tm_p6: "Kam'Etud takes a service commission on every successful transaction to cover platform operations.",
  tm_h7: "7. Responsibility", tm_p7: "Kam'Etud acts as an intermediary. The quality of work delivered is the student's responsibility; honoring the brief and payment is the client's responsibility.",
  tm_h8: "8. Applicable law", tm_p8: "These terms are governed by Cameroonian law. Any dispute will be submitted to the Dschang courts.",
  nf_title: "Oops! Page not found", nf_home: "Back to home",
  au_welcome_subtitle: "Access your account",
  au_google_signin: "Sign in with Google", au_google_signup: "Sign up with Google",
  au_or: "or", au_or_email: "or with an email",
  au_email: "Email", au_password: "Password",
  au_phone: "Phone", au_phone_number: "Phone number",
  au_forgot: "Forgot?", au_login: "Sign in", au_logging: "Signing in...",
  au_send_otp: "Send OTP code", au_sending: "Sending...",
  au_verify: "Verify and sign in", au_verifying: "Verifying...",
  au_resend: "Resend code", au_otp_label: "OTP code (6 digits)",
  au_login_ok: "Signed in", au_login_welcome: "Welcome to Kam'Etud!",
  au_err_creds: "Wrong email or password.", au_err_otp: "Invalid OTP code.",
  au_otp_sent: "Code sent!", au_otp_sent_desc: "An OTP code has been sent to",
  au_otp_err: "Could not send the code.",
  au_no_account: "No account yet?", au_have_account: "Already have an account?",
  au_signup: "Sign up", au_signin: "Sign in",
  au_create_account: "Create an account", au_choose_profile: "Choose your profile to start",
  au_complete_later: "You can complete your profile later",
  au_student_t: "Student", au_student_d: "Offer your skills and earn money helping others",
  au_client_t: "Client", au_client_d: "Find talented students for your projects and missions",
  au_signup_student: "Student sign up", au_signup_student_sub: "Join the community and offer your services",
  au_signup_client: "Client sign up", au_signup_client_sub: "Find talented students for your projects",
  au_first_name: "First name", au_last_name: "Last name", au_confirm: "Confirm",
  au_confirm_pw: "Confirm password", au_pw_mismatch: "Passwords do not match",
  au_pw_hint: "Min. 8 characters", au_city: "City", au_city_yours: "Your city",
  au_creating: "Creating...", au_create_btn: "Create my account",
  au_step1: "Personal info", au_step2: "Academic profile", au_step3: "Identity check",
  au_faculty: "Faculty / Major", au_faculty_eg: "Ex: Computer Science",
  au_level: "Level", au_level_select: "Select",
  au_uni: "University", au_bio: "Bio", au_bio_hint: "Introduce yourself...",
  au_skills: "Skills (min. 1)", au_doc_type: "ID document type",
  au_doc_select: "Choose", au_doc_warn: "Your documents will be reviewed by an administrator before your account is activated.",
  au_id_photo: "ID document photo", au_id_drop: "Drag or click",
  au_selfie: "Selfie with ID", au_selfie_hint: "Take a selfie",
  au_student_card: "Student card (optional)", au_student_card_hint: "Student card",
  au_accept: "I accept the", au_terms: "terms", au_and: "and the", au_privacy: "privacy policy",
  au_sent: "Submitted!", au_sent_d: "Check your email then sign in to complete verification.",
  au_err_register: "Sign up error. Check your information.",
  au_signup_ok: "Sign up successful!", au_signup_ok_d: "Check your email to activate your account.",
  au_or_student: "Student sign up", au_or_client: "Client sign up",
  au_google_redir: "Redirecting...", au_google_err: "Google error",
  au_continue_google: "Continue with Google",
  pf_verified: "Verified", pf_member_since: "Member since",
  pf_not_set: "Not set", pf_contact: "Contact",
  pf_cv: "CV", pf_photo: "Photo",
  pf_change_photo: "Change profile photo",
  pf_about: "About",
  pf_format_invalid: "Invalid format", pf_format_d: "JPG or PNG only.",
  pf_too_big: "File too large", pf_too_big_d: "Max 5 MB.",
  pf_photo_ok: "Photo updated", pf_photo_del: "Photo deleted",
  pf_del_confirm: "Delete your profile photo?",
  pf_up_err: "Upload error", pf_del_err: "Delete error",
  pf_stat_rating: "Rating", pf_stat_missions: "Missions",
  pf_stat_reviews: "Reviews", pf_stat_response: "Reply",
  pf_progress: "Progress",
  pf_tab_services: "Services", pf_tab_reviews: "Reviews", pf_tab_skills: "Skills",
  pf_order: "Order", pf_orders_count: "orders", pf_included: "included",
  pf_days_short: "d",
  pf_cv_gen: "Generated on", pf_cv_city: "City:", pf_cv_intro: "Introduction",
  pf_cv_skills: "Skills", pf_cv_jobs: "Completed missions",
  pf_cv_rating: "Average rating", pf_cv_level: "Level", pf_cv_response: "Response time",
  pf_cv_offered: "Offered service", pf_cv_from: "Starting from",
  pf_cv_footer: "Generated on Kam'Etud — the Cameroonian platform for student freelancers",
  pf_cv_title: "Kam'Etud — CV",
  // ---------- OrderPage ----------
  op_gig_404: "Gig not found",
  op_h: "Place order", op_by: "by",
  op_choose_tier: "Choose a tier",
  op_describe: "Describe your mission",
  op_describe_ph: "Precisely describe what you expect...",
  op_secure_pay: "Secure payment",
  op_escrow_t: "Escrow payment:",
  op_escrow_d: "Money held until validation.",
  op_phone: "Phone number",
  op_summary: "Summary", op_tier: "Tier", op_provider: "Provider",
  op_delay: "Delay", op_total: "Total",
  op_pay_btn: "Pay", op_processing: "Processing...",
  op_escrow_caption: "Secure escrow payment",
  op_login_required: "Sign in", op_login_required_d: "You must be signed in to order.",
  op_demo: "Demo", op_demo_d: "This is a demo service. Create real gigs to place an order.",
  op_mm_pending: "Mobile Money payment pending",
  op_mm_pending_d: "Order created. Charge failed — retry from My orders.",
  op_validate_phone: "Confirm on your phone",
  op_ussd: "Dial", op_to_confirm: "to confirm",
  op_request_sent_to: "A request of",
  op_has_been_sent_to: "has been sent to",
  st_pending: "Pending", st_accepted: "Accepted", st_in_progress: "In progress",
  st_delivered: "Delivered", st_revision: "Revision requested", st_revision_short: "Revision",
  st_completed: "Completed", st_disputed: "Disputed",
  st_cancelled: "Cancelled", st_refunded: "Refunded",
  mo_title: "My orders", mo_active: "Active", mo_past: "Past",
  mo_none_active: "No active order", mo_none_past: "No past order",
  mo_explore: "Explore", mo_by: "By", mo_tier: "Tier",
  mo_deliverable: "Deliverable submitted", mo_deliverable_default: "The student has submitted the deliverable.",
  mo_validate: "Validate", mo_revision: "Revision", mo_dispute: "Dispute",
  mo_review: "Rate", mo_publish: "Publish",
  mo_review_for: "Rate", mo_review_ph: "Your review...",
  mo_chat: "Chat", mo_send: "Send", mo_msg_ph: "Your message...",
  mo_revision_asked: "Revision requested", mo_dispute_open: "Dispute opened",
  mo_thanks: "Thanks!",
  mo_valid_ok: "Deliverable accepted!", mo_valid_ok_d: "Payment released to the student via Mobile Money.",
  mo_valid_pending: "Deliverable validated", mo_valid_pending_d: "Payment to the student is being processed — released shortly.",
  mm_title: "My missions", mm_demands: "Requests",
  mm_active: "Active", mm_done: "Done",
  mm_none_pending: "No request", mm_none_active: "No active mission",
  mm_none_done: "No completed mission",
  mm_client: "Client", mm_delivery: "Delivery", mm_revisions: "Revisions",
  mm_accept: "Accept", mm_decline: "Decline",
  mm_accepted: "Mission accepted!", mm_declined: "Mission declined",
  mm_submit: "Submit deliverable", mm_dragdrop: "Drop your files here",
  mm_note_client: "Note for the client...", mm_default_note: "Deliverable submitted",
  mm_submitted: "Deliverable submitted!", mm_chat_client: "Client chat",
  mm_no_msg: "No messages yet.",
  mg_title: "My Gigs", mg_create: "Create a gig",
  mg_none: "You have no gig. Create your first service!",
  mg_status_ok: "Status updated", mg_deleted: "Gig deleted",
  mg_published: "Published", mg_unpublished: "Unpublished",
  mg_draft: "Draft", mg_orders_count: "orders",
  mg_kyc_req: "Verification required", mg_kyc_req_d: "You must be verified (KYC) to publish a gig.",
  mg_unpublish: "Unpublish", mg_publish: "Publish",
  cg_title: "Publish a new gig", cg_general: "General information",
  cg_gig_title: "Title", cg_gig_title_ph: "Ex: Website creation",
  cg_gig_desc: "Description", cg_gig_desc_ph: "Describe your service...",
  cg_category: "Category", cg_choose: "Choose",
  cg_pricing: "Pricing (3 tiers)",
  cg_price: "Price (FCFA)", cg_delay: "Delay (days)",
  cg_tier_desc: "Description", cg_tier_desc_ph: "Ex: Landing page",
  cg_included: "Included", cg_feature_ph: "Ex: Responsive design",
  cg_add: "Add",
  cg_publish_now: "Publish now",
  cg_pn_yes: "Your service will be visible to clients.",
  cg_pn_no: "Unavailable: your identity must be verified by an admin.",
  cg_warn: "You can create gigs as", cg_warn_b: "draft",
  cg_warn_2: ". They will only be published after KYC validation by an administrator.",
  cg_saving: "Saving...", cg_publish_btn: "Publish the gig",
  cg_save_draft: "Save as draft",
  cg_gig_published: "Gig published!", cg_gig_published_d: "Your service is now visible.",
  cg_draft_saved: "Draft saved", cg_draft_saved_d: "You'll be able to publish it after identity validation.",
  rq_title: "Open requests",
  rq_subtitle: "Clients post their need and price, students propose",
  rq_new: "Post a request", rq_new_modal: "New request",
  rq_title_f: "Title", rq_title_ph: "Ex: Logo creation",
  rq_desc: "Description", rq_desc_ph: "Describe your need...",
  rq_budget: "Budget (FCFA)", rq_deadline: "Deadline",
  rq_publishing: "Posting...", rq_publish: "Post",
  rq_posted: "Request posted", rq_posted_d: "Students can now propose a price.",
  rq_none: "No open request for now.",
  rq_by: "by", rq_budget_caption: "Proposed budget",
  rd_404: "Request not found", rd_cancel: "Cancel the request",
  rd_cancelled: "Request cancelled",
  rd_propose: "Make a proposal (renegotiate the price)",
  rd_your_price: "Your price (FCFA)", rd_delay: "Delay (days)",
  rd_message: "Message", rd_message_ph: "Explain your approach...",
  rd_sending: "Sending...", rd_send: "Send proposal",
  rd_sent: "Proposal sent",
  rd_must_verify: "You must be verified to propose a price.",
  rd_proposals: "Proposals received",
  rd_no_proposals: "No proposal yet.",
  rd_delay_days: "day(s)",
  rd_accept: "Accept", rd_accepted: "Proposal accepted",
  rd_accepted_d: "The student will be notified.",
  mr_title: "My requests", mr_new: "New request",
  mr_none: "You haven't posted any request yet.",
  mr_publish: "Post a request",
  mr_st_open: "Open", mr_st_assigned: "Assigned",
  mr_st_cancelled: "Cancelled", mr_st_closed: "Closed",
  // ---------- Proposals ----------
  prp_title: "My proposals", prp_none: "You haven't made any proposal yet.",
  prp_status_pending: "Pending", prp_status_accepted: "Accepted", prp_status_rejected: "Rejected",
  prp_view_mission: "View the mission",
  // ---------- Income / Wallet ----------
  inc_title: "💰 My Income", inc_available: "Available balance",
  inc_pending: "Pending (Escrow)", inc_paid_missions: "Paid missions",
  inc_payout_settings: "Payout settings", inc_payout_phone: "Mobile Money number (for your payments)",
  inc_payout_help: "This number will be used to send your earnings after each validated mission.",
  inc_payout_ok: "Payout number updated",
  // ---------- Moderator ----------
  md_disputes: "Disputes", md_reports: "Reports",
  md_title: "Dispute management", md_navigation: "Navigation",
  md_open: "Open disputes", md_resolved: "Resolved",
  md_avg_time: "Avg time", md_open_status: "Open",
  md_tab_open: "Open", md_tab_resolved: "Resolved",
  md_none_open: "No dispute", md_none_resolved: "No resolved dispute",
  md_arbitrate: "Arbitrate", md_arbitration: "Arbitration",
  md_note_ph: "Moderator note...",
  md_refund: "Refund", md_validate: "Validate deliverable",
  md_report_abuse: "Report abuse",
  md_resolved_ok: "Dispute resolved",
  md_refund_ordered: "Refund ordered", md_deliverable_validated: "Deliverable validated",
  md_escalated: "Escalated to administrator",
  md_refunded: "Refunded", md_validated: "Validated",
  // ---------- Notifications (realtime) ----------
  nt_new_msg: "New message",
  nt_status: "Status",
  nt_new_mission: "New mission",
  nt_title: "Notifications", nt_mark_read: "Read", nt_none: "No notifications",
  ad_loading_img: "Loading…", ad_no_docs: "No document uploaded",
  ad_no_users: "No user found", ad_no_reports: "No reported content",
  ad_no_text: "No text", ad_no_orders: "No orders",
  ad_no_cats: "No categories", ad_no_cities: "No cities",
  ad_preview_img: "Image preview", ad_zoom_in: "Zoom in", ad_zoom_out: "Zoom out",
  ad_reset_zoom: "Reset", ad_download: "Download",
  ad_preview: "Preview", ad_download_err: "Download impossible",
  ad_report_title: "Kam'Etud — Admin Report",
  md_validate_deliv: "Validate deliverable",
};

const translations = { fr, en };
type Translations = typeof fr;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: Translations;
  locale: string;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>(() => {
    return (localStorage.getItem('kam_lang') as Language) || 'fr';
  });

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('kam_lang', lang);
  };

  return (
    <LanguageContext.Provider value={{
      language,
      setLanguage: handleSetLanguage,
      t: translations[language],
      locale: language === 'fr' ? 'fr-FR' : 'en-US',
    }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
};
